<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>super</artifactId>
        <groupId>org.imec.ivlab.ehealth.automation</groupId>
        <version>5.0.0</version>
        <relativePath>../super</relativePath>
    </parent>
    <artifactId>distribution</artifactId>
    <version>4.0.0</version>

    <build>
        <plugins>
                 
            <plugin>
                <artifactId>maven-resources-plugin</artifactId>
                <version>3.5.0</version>
                <executions>
                    <!-- Copy example config files : actors/patients/... -> now to build.install.directory (not installer) -->
                    <execution>
                        <id>copy-delivery-output</id>
                        <phase>install</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${build.install.directory}</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>${basedir}/src/main/resources-filtered/delivery_output</directory>
                                    <filtering>true</filtering>
                                </resource>
                            </resources>
                            <includeEmptyDirs>true</includeEmptyDirs>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
