<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>super</artifactId>
        <groupId>org.imec.ivlab.ehealth.automation</groupId>
        <version>5.0.0</version>
        <relativePath>../super</relativePath>
    </parent>
    <artifactId>viewer</artifactId>
    <properties>
        <itext.version>9.7.1</itext.version>
    </properties>
    <dependencies>

        <dependency>
            <groupId>org.imec.ivlab.ehealth.automation</groupId>
            <artifactId>core</artifactId>
            <version>5.0.0</version>
        </dependency>

        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
        </dependency>

        <dependency>
            <groupId>com.itextpdf</groupId>
            <artifactId>itext-core</artifactId>
            <version>${itext.version}</version>
            <type>pom</type>
            <!-- TODO You have to use your own version of itextpdf for local builds -->
            <!-- Uncomment these lines so it works on local
            <systemPath>${basedir}/lib/itext-core-9.7.1.pom</systemPath>
            -->
        </dependency>

        <dependency>
            <groupId>com.itextpdf</groupId>
            <artifactId>bouncy-castle-adapter</artifactId>
            <version>${itext.version}</version>
            <!-- TODO You have to use your own version of itextpdf for local builds -->
            <!-- Uncomment these lines so it works on local
            <systemPath>${basedir}/lib/bouncy-castle-connector-9.7.1.jar</systemPath>
            -->
            <!-- Needed as eHealth uses their own version of Bouncy Castle that could crash with it -->
            <exclusions>
                <exclusion>
                    <groupId>org.bouncycastle</groupId>
                    <artifactId>bcpkix-jdk18on</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.bouncycastle</groupId>
                    <artifactId>bcprov-jdk18on</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

    </dependencies>

    <build>

        <plugins>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
            </plugin>

        </plugins>


    </build>


</project>
