name: Spy Dependencies

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  spy_dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: 📂 Checkout repository
        uses: actions/checkout@v7

      - name: ☕ Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "21"
          cache: maven
      - name: ✨ Fix permissions
        run: |
          chmod u+x builder/release.sh    
      - name: 🔨 Build project with Maven
        shell: bash
        run: |
          cd builder && ./release.sh        
      - name: List dependancies 
        run: |
          mvn dependency:tree --file builder/pom.xml --batch-mode
      - name: Find duplicated dependancies
        run: |  
          mvn dependency:analyze-duplicate --file builder/pom.xml --batch-mode
